install.packages("ggplot2")
nstall.packages("stringi", dependencies = FALSE)
install.packages("caret")
install.packages("plyr")
install.packages("car")
install.packages("rlang")
install.packages("glue")
install.packages("dplyr")
install.packages("reshape2")
install.packages("ClustOfVar", dependencies = FALSE)
install.packages("FactoMineR")
install.packages("factoextra")          
install.packages("randomForest")
install.packages("MVA")
install.packages("corrplot")
install.packages("ca")
install.packages("randomForest")
install.packages("ade4")
install.packages("explor")
install.packages("devtools"
install.packages("scatterD3")
install_github("easyGgplot2", "kassambara")
install.packages("FactoMineR")
install.packages("clustertend", dependencies = FALSE)
install.packages("devtools")
devtools::install_github("kassambara/factoextra")
install.packages("seriation", dependencies = FALSE)
install.packages("TSP", dependencies = FALSE)
install.packages("registry", dependencies = FALSE)
install.packages("gclus", dependencies = FALSE)
install.packages("PerformanceAnalytics")

require(FactoMineR)
require(factoextra)
require(ggplot2)
require(stringi)
require(caret)
require(plyr)
require(car)
require(rlang)
require(glue)
require(dplyr)
require(reshape2)
require(ClustOfVar)
require(randomForest)
library(MVA)
library(corrplot)
require(ca)
require(randomForest)
require(ade4)
library(DBI)
library(tibble)
library(explor)
require(scatterD3)
library(devtools)
library(easyGgplot2)
library("FactoMineR")
library("factoextra")
library(clustertend)
library(TSP)
library(registry)
library(gclus)
library(seriation)
library("PerformanceAnalytics")
